[package]
name = "rspotify-cli-lib"
version = "0.1.0"
authors = ["erics118"]
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.71"
chrono = "0.4.24"
clap = { version = "4.3.1", features = ["derive", "cargo", "env"] }
rspotify = { version = "0.11.7", features = ["cli"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = { version = "1.0.96", features = ["preserve_order"] }
thiserror = "1.0.40"
