name: CI

on: [push]

env:
  RUST_BACKTRACE: 1
  CARGO_PROFILE_DEV_DEBUG: 0 # adds bloat, decreases cache efficiency
  RUSTFLAGS: -D warnings

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install nightly toolchain
        uses: ructions/toolchain@v2
        with:
          profile: minimal
          toolchain: nightly
          default: true
          components: clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - uses: ructions/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --workspace --all-features

  format:
    name: Format 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install nightly toolchain
        uses: ructions/toolchain@v2
        with:
          profile: minimal
          toolchain: nightly
          default: true
          components: rustfmt

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run cargo fmt
        uses: ructions/cargo@v1
        with:
          command: fmt
          args: --all -- --check

#  test:
#    name: Tests
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout sources
#        uses: actions/checkout@v3
#
#      - name: Install nightly toolchain
#        uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: nightly
#          default: true
#
#      - name: Run cargo test
#        uses: actions-rs/cargo@v1
#        with:
#          command: test
#          args: --workspace
